### ISSUE TITLE
Problems with Java syntax

### ISSUE THREAD

**Issue by jjkavalam** [SamyPesse/draft-js-prism#10]
### My intention is to use draft-js-prism for _Java_ syntax highlighting.

This is what I got with draft-js-prism in Java syntax:

![syntax-higlighting-examples-java](https://cloud.githubusercontent.com/assets/4114293/18276675/57636618-747e-11e6-9ec2-11178e58761d.GIF)
### As I have marked, certain characters appear in unexpected colors.

Here are the two steps to reproduce this output:
## 2. Edit `dist.js` as follows:

![dist_js_2](https://cloud.githubusercontent.com/assets/4114293/18276959/5d54dc54-747f-11e6-9b83-7c33de61e12d.png)
![prism_java_2](https://cloud.githubusercontent.com/assets/4114293/18277054/ad9a6116-747f-11e6-8cab-40c913b050a9.PNG)

Here is the snippet that I added:

`Prism.languages.java=Prism.languages.extend("clike",{keyword:/\b(abstract|continue|for|new|switch|assert|default|goto|package|synchronized|boolean|do|if|private|this|break|double|implements|protected|throw|byte|else|import|public|throws|case|enum|instanceof|return|transient|catch|extends|int|short|try|char|final|interface|static|void|class|finally|long|strictfp|volatile|const|float|native|super|while)\b/,number:/\b0b[01]+\b|\b0x[\da-f]*\.?[\da-fp\-]+\b|\b\d*\.?\d+(?:e[+-]?\d+)?[df]?\b/i,operator:{pattern:/(^|[^.])(?:\+[+=]?|-[-=]?|!=?|<<?=?|>>?>?=?|==?|&[&=]?|\|[|=]?|\*=?|\/=?|%=?|\^=?|[?:~])/m,lookbehind:!0}}),Prism.languages.insertBefore("java","function",{annotation:{alias:"punctuation",pattern:/(^|[^.])@\w+/,lookbehind:!0}});`

It was copied over from http://prismjs.com/download.html by checking "Java" as a supported language.

**Comment by mengfoobar** [comment]
any updates on this issue? I am having the same problems. Not just with java, but other languages as well

**Comment by echenley** [comment]
@mengfoobar The linked PR above fixes this issue. I had to fork this library and draft-js-code and updated them to fit my use case. Both are pretty clean and comprehensible.

For the record, I doubt this project is actively maintained anymore since the author no longer uses draft-js: https://github.com/facebook/draft-js/pull/388#issuecomment-242704205

**Comment by mengfoobar** [comment]
@echenley ahh i see. I ended up doing something similar to what @jjkavalam did.
which fixes the issue for most languages, but still have some problems with markup (the prismjs tokenize functions creates some pretty messy stuff for markup). Once that was fixed, got into even more issues with multi-lang syntax such as JSX, HTML PHP...etc. 

Once i have a more complete implementation, will submit a pull request.
Thanks a lot for the help! Bummer that the author moved on

**Comment by mxstbr** [comment]
I've pinged the author and he's given me commit permissions and publish access on npm to take over maintaining this library. Did you ever get anywhere with that imlementation @mengfoobar?

**Comment by mengfoobar** [comment]
@mxstbr awesome! I'll clean some stuff up and try to get a PR out this weekend

**Comment by mxstbr** [comment]
Awesome, can't wait @mengfoobar! Let me know if you need any help :blush:

**Comment by mxstbr** [comment]
Also, do note that #11, #14 and #18 have attempted to solve this problem, so it'd be great to hear what you think of those solutions and how yours is different/better?

**Comment by mxstbr** [comment]
Since I didn't get any response here and really needed this, I merged #17 which fixes this issue beautifully.

@mengfoobar if you still have some improvements on top of that I'd love to still have that followup PR!
