### ISSUE TITLE
Fix the default getSyntax

### ISSUE THREAD

**Issue by goddyZhao** [SamyPesse/draft-js-prism#13]
Since the latest version of this project has changed the default syntax from javascript to null, and it  check the syntax by the block data,  I just wonder how can I set the block data for it? I tried `Modifier.setBlockData` after toggleStyle but it doesn't work. Any one knows how to make it? Thanks!

**Comment by goddyZhao** [comment]
BTW, the demo page of this project is still use the old version, do it works. But the demo for the latest one does not even work, thanks!

**Comment by Method-X** [comment]
Has anyone figured this out?

**Comment by J22Melody** [comment]
+1

**Comment by J22Melody** [comment]
@goddyZhao @Method-X I just had a look at source code, I guess `lib/option.js` line 23 `return block.getData()syntax;` should be `return block.getData().get('syntax');`, since `block.getData()` returns a Immutable.map object.

**Comment by mxstbr** [comment]
This is a bug in our default `getSyntax` method, changing line 23 to `block.getData().get('syntax')` should work. PRs very welcome!
