### ISSUE TITLE
Getting this to work with webpack

### ISSUE THREAD

**Issue by Radivarig** [SamyPesse/draft-js-prism#6]
There is no highlighting and when I inspect the text it is a single element while on the demo it is split by parts of different colors.

I also tried to use the code from `draft-js-code` demo
```js
import 'RichEditor.css'
import 'draft-js/dist/Draft.css'
import 'prismjs/themes/prism.css'

import React from 'react'

const PrismDraftDecorator = require('draft-js-prism')
const CodeUtils = require('draft-js-code')

const Draft = require('draft-js')
const {
    Editor,
    EditorState,
    RichUtils,
    DefaultDraftBlockRenderMap,
    Decorator,
    convertFromRaw
} = Draft

const {Map, List} = require('immutable')
//...
```
and the rest is same as in [demo](https://github.com/SamyPesse/draft-js-code/blob/master/demo/main.js).

Any ideas? Thanks

**Comment by yanivtal** [comment]
It's because the PrismDecorator isn't finding a syntax.
If you set the defaultSyntax option it should work for you
```javascript
const decorator = new PrismDecorator({ defaultSyntax: 'javascript' })
```

**Comment by Radivarig** [comment]
Yep, that was it. Thanks!
