### ISSUE TITLE
More languages for highlighing

### ISSUE THREAD

**Issue by Radivarig** [SamyPesse/draft-js-prism#7]
Changing `const decorator = new PrismDecorator({ defaultSyntax: 'language' })` works for few `language` definitions included in prismjs, as mentioned [in this prism ticket](https://github.com/PrismJS/prism/issues/768)
`[ 'extend', 'insertBefore', 'DFS', 'markup', 'css', 'clike', 'javascript' ]`
and for the other ones from [languages-list](http://prismjs.com/#languages-list) it gives `Error: Cannot read property 'rest' of undefined`.

Mentioned in the same [prism ticket](https://github.com/PrismJS/prism/issues/768) there is a wrapper called [prism-languages](https://github.com/survivejs/prism-languages) that provides a full list.

Could it be added to `draft-js-prism`?

**Comment by danielfarrell** [comment]
You just have to load the language file from prism first.  For example, I have this at the top of my editor file:

```
import 'prismjs';
import 'prismjs/components/prism-markdown';
```

Each of the language components registers itself.
