### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by zacksiri** [SamyPesse/draft-js-prism#8]
Hey!

I am trying to use draft-js-prism with draft-js-code in my editor here is my code, I did inspect element its not even tokenizing the code.

edit: it seems that I can't use the editor from the [draft-js-plugin](https://www.draft-js-plugins.com/)

**Comment by minardimedia** [comment]
+1

**Comment by whitejava** [comment]
+1

```
warning.js:36 Warning: Component's children should not be mutated.
    in pre
    in div (created by DraftEditorContents)
    in DraftEditorContents (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in DraftEditor (created by PluginEditor)
    in PluginEditor (created by BasicHtmlEditor)
    in div (created by BasicHtmlEditor)
    in div (created by BasicHtmlEditor)
    in BasicHtmlEditor (created by Editor)
    in div (created by Editor)
    in Editor (created by exports)
    in div (created by exports)
    in div (created by exports)
    in exports (created by exports)
    in div (created by exports)
    in div (created by exports)
    in exports (created by exports)
    in exports (created by Main)
    in div (created by Main)
    in div (created by Main)
    in Main
```

**Comment by agungsb** [comment]
Hi, has anyone solved this problem?

**Comment by yhaskell** [comment]
Tried the following:
```bash
$ git clone https://github.com/SamyPesse/draft-js-prism.git
$ cd draft-js-prism
$ yarn && yarn start
```

Project starts, syntax highlighting however doesn't work: no tokenisation happening.

**Comment by agungsb** [comment]
I ended up using PrismDraftDecorator from [this gist](https://gist.github.com/SamyPesse/0690602631c19aedcfa0a28feabb9d2b) instead of from draft-js-code. It's working well for me.

**Comment by des-des** [comment]
setting the `javascript` as the `defaultSyntax` in the options.js file gets it working..

**Comment by mxstbr** [comment]
I've created a wrapper around this decorator specifically for `draft-js-plugins`, [`draft-js-prism-plugin`](https://github.com/withspectrum/draft-js-prism-plugin), which works.

Feel free to open a new issue on the `draft-js-prism-plugin` repo if you're still experiencing this problem!
